// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3KrRd23XlKMKcaH8teN052wuBNBY3NRY',
    appId: '1:907291847297:web:ac701ae64b1a0cb44c3b80',
    messagingSenderId: '907291847297',
    projectId: 'encrypt-decrypt-app-764f4',
    authDomain: 'encrypt-decrypt-app-764f4.firebaseapp.com',
    storageBucket: 'encrypt-decrypt-app-764f4.appspot.com',
    measurementId: 'G-BDZP90MC7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7fsjIRH8eC4TJxblT9iba93VNXyRQUCQ',
    appId: '1:907291847297:android:7793156fbe766c9d4c3b80',
    messagingSenderId: '907291847297',
    projectId: 'encrypt-decrypt-app-764f4',
    storageBucket: 'encrypt-decrypt-app-764f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ3ps7N_BJwcuqX070qEHy4uqkNKeX5tE',
    appId: '1:907291847297:ios:bddbfdc03d2014eb4c3b80',
    messagingSenderId: '907291847297',
    projectId: 'encrypt-decrypt-app-764f4',
    storageBucket: 'encrypt-decrypt-app-764f4.appspot.com',
    iosClientId: '907291847297-h4snca03auecro0hi251bl0ft1608ec0.apps.googleusercontent.com',
    iosBundleId: 'com.example.encryptDecryptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ3ps7N_BJwcuqX070qEHy4uqkNKeX5tE',
    appId: '1:907291847297:ios:468a35c168c7f40a4c3b80',
    messagingSenderId: '907291847297',
    projectId: 'encrypt-decrypt-app-764f4',
    storageBucket: 'encrypt-decrypt-app-764f4.appspot.com',
    iosClientId: '907291847297-qjehil22fqm0q4c2jac4d2holc7haao7.apps.googleusercontent.com',
    iosBundleId: 'com.example.encryptDecryptApp.RunnerTests',
  );
}
